{{- with .Values.wopibridge }}
{{- if .enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wopiserver.fullname" $ }}-{{ .name }}
  labels:
    {{- include "wopibridge.labels" $ | nindent 4 }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      {{- include "wopibridge.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "wopibridge.selectorLabels" $ | nindent 8 }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image.repository }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          volumeMounts:
            - name: {{ .name }}-secret
              mountPath: /var/run/secrets
          {{- if .extraVolumeMounts }}
            {{- toYaml .extraVolumeMounts | nindent 12 }}
          {{- end }}
          env:
            - name: "WOPIBRIDGE_URL"
              value: {{ template "wopibridge.url" $ }}
          {{- if .env }}
            {{- range $name, $value := .env }}
            - name: "{{ $name }}"
              value: "{{ $value }}"
            {{- end }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
      volumes:
        - name: {{ .name }}-secret
          secret:
            secretName: {{ include "wopiserver.fullname" $ }}-{{ .name }}-secret
      {{- if .extraVolumes }}
      {{- toYaml .extraVolumes | nindent 6 }}
      {{- end }}
{{- end }}
{{- end }}
